// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lttzkkpwgcydvliixqcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dHpra3B3Z2N5ZHZsaWl4cWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTgzMjMsImV4cCI6MjA2NjY5NDMyM30.YOfd4-o1qSusJt6aHDQP8ajCjT2nrwyBBgNrNd7TTzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);